# Docker Compose configuration

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fluvia
      POSTGRES_USER: fluvia_user
      POSTGRES_PASSWORD: fluvia_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=fluvia
      - DB_USER=fluvia_user
      - DB_PASSWORD=fluvia_password
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
