[deploy]
startCommand = "pnpm install --frozen-lockfile && pnpm run build && node dist/index.js"
healthcheckPath = "/v1/healthcheck"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"