[deploy]
startCommand = "npm install -g pnpm@10.14.0 && pnpm install --frozen-lockfile && pnpm run build && node dist/index.js"
healthcheckPath = "/v1/healthcheck"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"
